AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
 
  #Lambdas
  RedditGenerateCaptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./application/serverless/aws/lambda/reddit-generate-capitons
      Handler: index.handler
      Runtime: nodejs18.x
      # Environment:
      #     Variables:
      #       HELLO_TABLE_NAME: !Ref ExampleTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - index.ts